export default {
  id: '',
  flags: '',
  status: '',
  endpoint: '',
  loan_type: '',
  source_id: '',
  created_at: '',
  deleted_at: '',
  loanpro_id: '',
  updated_at: '',
  source_user: '',
  applicant_id: '',
  decision_num: '',
  request_type: '',
  stipulations: '',
  source_app_id: '',
  coapplicant_id: '',
  application_num: '',
  decline_reasons: '',
  has_coapplicant: '',
  endpoint_original: '',
};
