export default {
  id: '',
  pti: '',
  found: '',
  payment: '',
  created_at: '',
  deleted_at: '',
  ltv_retail: '',
  updated_at: '',
  date_opened: '',
  interest_apr: '',
  ltv_wholesale: '',
  original_term: '',
  application_id: '',
  remaining_term: '',
  not_found_reason: '',
  original_balance: '',
  remaining_balance: '',
};
