export enum BlockTypes {
  FORMULA = 'Formula',
  IF_CONDITION = 'If Condition',
  SPLIT_PATH = 'Split Path',
  GROUP = 'Group of Blocks',
  CONDITION_TABLE = 'Condition Table',
  GO_TO = 'Go To Block',
  API_CALL = 'Api Call',
  ASYNC_RESPONSE = 'Async Response',
  SUB_WORKFLOW = 'Subworkflow',
  CUSTOM_CODE = 'Custom Code',
  CONVERTER = 'Converter',
  JSONATA = 'Jsonata',
  APP_STATUS_CHANGE = 'Application Status Change',
  ALERT = 'Alert',
  LOOP = 'Loop',
  DB_CONNECTION = 'DB Connection',
  S3_UPLOAD = 'S3 Upload',
  SFTP_UPLOAD = 'SFTP Upload',
}
