import React from 'react';
import { IWorkflowContext } from './types';

export const WorkflowContext = React.createContext<IWorkflowContext>({
  isEditing: true,
  handleRunTest: null,
  testExecution: null,
  selectedWorkflow: null,
  selectedNode: null,
  nodes: null,
  edges: null,
  onNodesChange: null,
  onEdgesChange: null,
  onPanelClick: null,
  onEdgeClick: null,
  selectedEdge: null,
  isEditorModalOpen: false,
  setIsEditorModalOpen: null,
  selectedModalType: null,
  setSelectedModalType: null,
  isActionLoading: false,
  refetchWorkflow: null,
  setSelectedNode: null,
  setSelectedEdge: null,
  isDeployed: false,
  testsLoading: false,
  selectedTest: null,
  tests: [],
  testName: null,
  testBody: null,
  testSuccessCriteria: null,
  setSelectedTest: null,
  setTestName: null,
  setTestBody: null,
  setTestSuccessCriteria: null,
  isTesting: false,
  setIsTesting: null,
  handleSaveTest: null,
  onDuplicateTest: null,
  onDeleteTest: null,
  refetchTestLastExecution: null,
  refetchTests: null,
  onTestRename: null,
  onNewTest: null,
  onModalClose: null,
  setIsEditing: null,
  isTraceMode: false,
  setIsTraceMode: null,
  traceSteps: [],
  setTraceSteps: null,
});
