name: publish on github

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm install storybook
      - run: npm install @storybook/addon-links
      - run: npm install @storybook/addon-onboarding
      - run: npm install @storybook/addon-actions
      - run: npm install @storybook/addon-controls
      - run: npm install @storybook/addon-docs
      - run: npm install @storybook/addon-essentials
      - run: npm install @storybook/addon-storysource      
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}